### ISSUE TITLE
Error: System "sb-cltl2" not found when loading Lisp-Stat into Allegro CL 10.1 (commercial version)

### ISSUE THREAD

**Issue by jdwatton** [Lisp-Stat/data-frame#27]
Seems to be an issue with data-frame. I get the error message: Error: System "sb-cltl2" not found. I was told this would be an easy fix. I hope so. I really want to run Lisp-State in ACL.
-John

**Comment by snunez1** [comment]
I have requested a license of ACL so I can support Lisp-Stat on that platform; hopefully it will happen soon.  In the meantime, you can try modifying the [describe-object](https://github.com/Lisp-Stat/data-frame/blob/ebd11b1ad55478d0e8612b1559fd1750400435d6/src/data-frame.lisp#L567) function to conditionalise on ACL and use  its [variable-information](https://franz.com/support/documentation/current/system-ops.html#variable-information) function.  Franz seems to support CLtL2 [environments](https://franz.com/support/documentation/current/environments.html), so there's certainly a way to make this work.

**Comment by jdwatton** [comment]
Thanks for the hints. Tried the conditionalize on variable-information, but it did not work. The load never makes it to the data-frame.lisp file. Seems like something else wants to load a system called sb-cltl2, and that system doesn’t exist? I wish I knew more about quickload and defsystem but I don’t.

Good luck getting an ACL license (without having to pay).
--John

CG-USER(2): (QUICKLISP:QUICKLOAD :LISP-STAT :VERBOSE T :EXPLAIN T)
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\lisp-stat-20221106-git\lisp-stat.asd
; Autoloading for class ECHO-STREAM:
;   Fast loading from bundle code\STREAMA.fasl.
To load "lisp-stat":
  Load 1 ASDF system:
    lisp-stat
; Loading "lisp-stat"
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\alexandria-20220707-git\alexandria.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\alexandria-plus-20221106-git\alexandria+.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\array-operations-1.0.0\array-operations.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\let-plus-20191130-git\let-plus.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\anaphora-20220220-git\anaphora.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\data-frame-20221106-git\data-frame.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\numerical-utilities-20221106-git\num-utils.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\select-20221106-git\select.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\statistics-20221106-git\statistics.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\distributions-20221106-git\distributions.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cephes.cl-20221106-git\cephes.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cffi-20221106-git\cffi.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\trivial-features-20211209-git\trivial-features.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\babel-20200925-git\babel.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\special-functions-20221106-git\special-functions.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\float-features-20221106-git\float-features.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\documentation-utils-20190710-git\documentation-utils.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\trivial-indent-20210531-git\trivial-indent.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\conduit-packages-20221106-git\org.tfeb.conduit-packages.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\duologue-20220707-git\duologue.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\clavier-20210531-git\clavier.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cl-ppcre-20220220-git\cl-ppcre.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\closer-mop-20221106-git\closer-mop.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\chronicity-20190202-git\chronicity.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cl-interpol-20221106-git\cl-interpol.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cl-unicode-20210228-git\cl-unicode.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\flexi-streams-20220220-git\flexi-streams.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\trivial-gray-streams-20210124-git\trivial-gray-streams.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\named-readtables-20220331-git\named-readtables.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\local-time-20220707-git\local-time.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cl-fad-20220220-git\cl-fad.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\bordeaux-threads-v0.8.8\bordeaux-threads.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cl-ansi-text-20211020-git\cl-ansi-text.asd
; Loading C:\Users\JWatton\quicklisp\dists\quicklisp\software\cl-colors2-20211020-git\cl-colors2.asd
Error: System "sb-cltl2" not found
[condition type: SYSTEM-NOT-FOUND]To load "lisp-stat":
  Load 1 ASDF system:
    lisp-stat
; Loading "lisp-stat"
Error: Dependency looping -- already tried to load sb-cltl2
(:LISP-STAT)

**Comment by snunez1** [comment]
I have pushed some changes to make ACL work and confirmed a clean compile from scratch (deleted the fasl directory).  Tutorials through plotting 'getting started' confirmed to work.

**Comment by jdwatton** [comment]
Thank-you. Still, I do not know how to use quicklisp:quickload to get a version lisp-stat that works. Same error: Error: System "sb-cltl2" not found. I know next to nothing about quicklisp and github, so I am at a loss as to how to start from a clean slate with the load of lisp-stat and the dependent systems.

**Comment by snunez1** [comment]
It sounds like you're using an old version.  Try `(slot-value (asdf:find-system 'data-frame) 'asdf:version)`.  If it returns anything other than 1.3.3, you're using an outdated version.

There are instructions for [installing from source](https://github.com/Lisp-Stat/lisp-stat) in the main Lisp-Stat repo.  Quicklisp isn't updated frequently, and so won't have these latest changes.

**Comment by jdwatton** [comment]
Yes, (slot-value (asdf:find-system 'data-frame) 'asdf:version) returns 1.3.1. Not sure of my next move.

**Comment by snunez1** [comment]
I'd say your next move is to follow the instructions given to you in the last comment.

**Comment by jdwatton** [comment]
Thanks for your patience. Okay, I tried the instructions on: GitHub - Lisp-Stat/lisp-stat: Lisp-Stat main system<https://github.com/Lisp-Stat/lisp-stat?tab=readme-ov-file#installation>
I do get further along, but I get stuck on loading the third party dependencies. Seems like static-vectors need gcc, which obviously, I do not have installed on my computer. Maybe just easier to get sbcl, although that seems like defeat since I’ve found ACL all I needed since the early 1990s.  I assume sbcl comes with gcc.

CG-USER(3): (ql:quickload :static-vectors)
To load "static-vectors":
  Load 1 ASDF system:
    static-vectors
; Loading "static-vectors"
; gcc -o "C:\Users\JWatton\AppData\Local\cache\common-lisp\acl-10.1s-win-x64\C\Users\JWatton\quicklisp\dists\quicklisp\software\static-vectors-v1.8.9\src\ffi-types__grovel-tmpcjmv9jbs.obj" -c -m64 "-IC:\Users\JWatton\quicklisp\dists\quicklisp\software\cffi-20231021-git\\" "C:\Users\JWatton\AppData\Local\cache\common-lisp\acl-10.1s-win-x64\C\Users\JWatton\quicklisp\dists\quicklisp\software\static-vectors-v1.8.9\src\ffi-types__grovel.c"
Error: "starting shell command" resulted in error: No such file or directory [errno=2].
[condition type: GROVEL-ERROR]
(:STATIC-VECTORS)
CG-USER(4):

**Comment by snunez1** [comment]
Well, at least the problem is being narrowed down.  I'd suggest opening an [issue with the static-vectors project](https://github.com/sionescu/static-vectors/issues) and see if they can help you.  SBCL does not come with gcc.  Gcc is a compiler that must be installed.  Linux systems will have it built in, so you must be on MS Windows or MacOS.

Trying with SBCL or CCL would be a good way to see if it's the environment or not.

**Comment by jdwatton** [comment]
Yes, I am on Windows. After installing gcc, Lisp-stat and all the dependencies load in ACL 10.1. There are a lot of warnings. There has been at least one error running Lisp-Stat examples. I will keep notes and file a report.

**Comment by snunez1** [comment]
@jdwatton, is this still an issue for you?
